// Copies contract ABIs out of contracts/out into server/src/abis.ts (and
// web/lib/abis.ts when web exists). Run after `forge build`.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const out = path.join(root, "contracts/out");

const contracts = {
  vaultAbi: "CampaignVault.sol/CampaignVault.json",
  auctionAbi: "AdAuction.sol/AdAuction.json",
  settlementAbi: "PayoutSettlement.sol/PayoutSettlement.json",
  usdcAbi: "MockUSDC.sol/MockUSDC.json",
};

let ts = "// AUTO-GENERATED by server/scripts/gen-abis.mjs — do not edit.\n";
for (const [name, rel] of Object.entries(contracts)) {
  const artifact = JSON.parse(readFileSync(path.join(out, rel), "utf8"));
  ts += `export const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`;
}

const targets = [path.join(root, "server/src/abis.ts")];
const webLib = path.join(root, "web/lib");
if (existsSync(path.join(root, "web"))) {
  mkdirSync(webLib, { recursive: true });
  targets.push(path.join(webLib, "abis.ts"));
}
const fnDir = path.join(root, "supabase/functions/server");
if (existsSync(fnDir)) targets.push(path.join(fnDir, "abis.ts"));
for (const t of targets) {
  writeFileSync(t, ts);
  console.log("wrote", path.relative(root, t));
}
